---
title: "vocabulary"
output: html_notebook
---


```{r, echo=TRUE}
library(xlsx)
library(qdap)
library(ggplot2)

setwd("../data/")
Info<-read.xlsx("InaugurationInfo.xlsx",1)
date<-read.csv("date.csv")
```


```{r, echo=TRUE}
setwd("../data/InauguralSpeeches/")

count<-function(name){
  n_sentence<-length(sent_detect(name))
  n_word<-word_count(name)
  
  return(c(n_sentence,n_word))
}


filename<-paste("inaug",Info$File,"-",Info$Term,".txt",collapse = NULL,sep="")

matrix_count<-matrix(NA,ncol=3,nrow = 58)

for(i in 1:(length(filename)-1)){
  
  text<-readLines(filename[i],warn = FALSE)
  matrix_count[i,2:3]<-count(text)
  
}


count<-as.data.frame(matrix_count)
colnames(count)<-c("file","sentence","word")
count$file<-paste(Info$File,Info$Term)
count$var<-count$word/count$sentence
count$party<-Info$Party




date$Date<-as.character(date$Date)
year<-substr(date$Date,nchar(date$Date)-3,nchar(date$Date))
year<-year[year!=""]

count$year<-year
count$year<-as.numeric(count$year)
```


```{r, echo=TRUE, fig.height=8, fig.width=11}
p<-ggplot(data=count)+
  geom_point(mapping = aes(x=year,y=var,col=party))+
  geom_line(mapping = aes(x=year,y=var,col="blue"))+
  geom_text(x=1942,y=20,label="ww2")+
  geom_text(x=1916,y=25,label="ww1")+
  geom_text(x=1862,y=25,label="civil war")+
  geom_text(x=1947,y=15,label="cold war start")+
  geom_text(x=1991,y=15,label="cold war end")

ggplotly(p)
```





```{r, echo=TRUE, fig.height=8, fig.width=11}
p<-ggplot(data=count)+
  geom_point(mapping = aes(x=year,y=var,col=party))+
  geom_line(mapping = aes(x=year,y=var,col="red"))+
  geom_text(x=1837,y=37,label="Panic 1837")+
  geom_text(x=1893,y=36,label="Panic 1893")+
  geom_text(x=1907,y=32,label="Panic 1907")+
  geom_text(x=1929,y=22,label="wall street")+
  geom_text(x=2008,y=22,label="global")
  
ggplotly(p)
```


```{r, echo=TRUE, fig.height=8, fig.width=5}

ggplot(data=count[count$party=="Republican"|count$party=="Democratic",])+
  geom_boxplot(mapping = aes(x=year,y=var,col=party))
```